name: Apex Code/Design Tech Debt Scanner
on:
  pull_request:
    types: [ labeled ]
  workflow_dispatch:
jobs:
  analyze:
    if: ${{ github.event.label.name == 'review' }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install SFDX CLI and Scanner
        run: |
          npm install sfdx-cli -g
          sfdx plugins:install @salesforce/sfdx-scanner

      - name: Run SFDX Scanner - Report findings as comments
        uses: mitchspano/sfdx-scan-pull-request@v[LATEST_VERSION_HERE]
        with:
          pmdconfig: level-0-tech-debt-ruleset.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
